[package]
name = "vit-servicing-station-lib"
version = "0.1.0-ci-test.1"
authors = ["danielsanchezq <daniel.sanchez@iohk.io>"]
edition = "2018"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-graphql = "1.18.2"
async-graphql-warp = "1.18.1"
async-trait = "0.1.33"
base64 = "0.12.1"
chrono = { version = "0.4", features = ["serde"] }
diesel = { version = "1.4.5", features = ["sqlite", "r2d2"] }
diesel_migrations = "1.4.0"
dotenv = "0.9.0"
itertools = "0.9.0"
log = { version = "0.4.11", features = ["serde"] }
logging-lib = { path = "../logging-lib" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.53"
simplelog = "0.8.0"
structopt = "0.3.14"
thiserror = "1.0"
tokio = { version = "0.2.21", features = ["macros", "signal"] }
warp = { version = "0.2", features = ["tls"] }

# This solves building on windows when sqlite3lib is not installed or missing in the `$PATH`
# as it happens with the github actions pipeline associated to this project.
[target.'cfg(windows)'.dependencies]
libsqlite3-sys =  { version = "0.9.3", features = ["bundled"] }

[dev-dependencies]
tempfile = "3"
