[package]
name = "vit-servicing-station-cli"
version = "0.1.0-ci-test.1"
authors = ["danielsanchezq <daniel.sanchez@iohk.io>"]
edition = "2018"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.12.1"
chrono = "0.4.13"
csv = "1.1"
rand = "0.7.3"
structopt = "0.3.14"
serde = { version = "1.0", features = ["derive"] }
tempfile = "3.1.0"
vit-servicing-station-lib = { path = "../vit-servicing-station-lib" }

[dev-dependencies]
diesel = { version = "1.4.5", features = ["sqlite", "r2d2"] }
diesel_migrations = "1.4.0"
